START TRANSACTION;

DROP DATABASE mexflix_36;

CREATE DATABASE mexflix_36;

USE mexflix_36;

CREATE TABLE genres(
  genre_id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  genre_name VARCHAR(15) NOT NULL
);

INSERT INTO genres ( genre_name ) VALUES
  ('Action'),
  ('Adventure'),
  ('Animation'),
  ('Biography'),
  ('Comedy'),
  ('Crime'),
  ('Documentary'),
  ('Drama'),
  ('Family'),
  ('Fantasy'),
  ('Film-Noir'),
  ('Game-Show'),
  ('History'),
  ('Horror'),
  ('Music'),
  ('Musical'),
  ('Mystery'),
  ('News'),
  ('Reality-TV'),
  ('Romance'),
  ('Sci-Fi'),
  ('Sport'),
  ('Talk-Show'),
  ('Thriller'),
  ('War'),
  ('Western');

CREATE TABLE movies(
  imdb_id CHAR(9) NOT NULL PRIMARY KEY,
  title VARCHAR(80) NOT NULL,
  plot TEXT,
  genres VARCHAR(80) NOT NULL,
  premiere DATE NOT NULL,
  poster VARCHAR(255) DEFAULT './img/no-poster.jpg',
  poster_bg VARCHAR(255) DEFAULT './img/no-poster-bg.jpg',
  trailer VARCHAR(255) DEFAULT '/img/no-trailer.jpg',
  rating DECIMAL(2,1) UNSIGNED DEFAULT NULL,
  category ENUM('Movie', 'Serie') NOT NULL
);

INSERT INTO movies ( imdb_id, title, plot, genres, premiere, poster, poster_bg, trailer, rating, category ) VALUES
  ('tt0380538', 'Matando Cabos', 'Oscar Cabos (Pedro Armendáriz Jr.) es un terrible magnate al que todos deben respeto, para mala fortuna de "Jaque" (Tony Dalton) y "Mudo" (Kristoff Raczynski), ellos lo tienen metido en un baño inconsciente. Esta problemática situación comenzó cuando Cabos descubrió a "Jaque" teniendo relaciones sexuales con su hija Paulina Cabos (Ana Claudia Talancon), lo cual le valió una golpiza y ahora una muy mala experiencia. Las vivencias de este par de amigos y su mala fortuna, son el tema de esta historia que nos demuestra que las coincidencias tienen consecuencias...', 'Action, Adventure, Comedy', '2004-07-16', 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/YPpSCRURlQ5RQIWwNsg8hLyENI.jpg', 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/xTiJA01wBwapRC4Golk1ignqJHw.jpg', '<iframe width="560" height="315" src="https://www.youtube.com/embed/nujJ3sXSU18" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>', 7.6, 'Movie'),
  ('tt0446029', 'Scott Pilgrim vs. the World', 'Les presentamos al encantador y desempleado Scott Pilgrim (Michael Cera), bajista de un grupo “garage” de lo más corriente, los Sex Bob-omb. Este joven de 22 años acaba de conocer a la chica de sus sueños… la de verdad. ¿Cuál es el problema a la hora de conquistar a Ramona Flowers (Mary Elizabeth Winstead)? Los siete ex de la chica están decididos a matar a Scott.Scott Pilgrim nunca ha tenido problemas para echarse novia. Las dificultades aparecen cuando quiere cortar. Mientras intenta deshacerse de la última conquista, Ramona irrumpe en su vida, pero no tarda en descubrir que la mujer deseada arrastra un bagaje nada tranquilizador: sus ex controlan su vida amorosa y están dispuestos a hacer lo que sea para eliminar la competencia.', 'Action, Comedy, Romance', '2010-07-27', 'https://image.tmdb.org/t/p/original/lafRuPbjEQrrHG9QEaoyV2znZC.jpg', 'https://image.tmdb.org/t/p/original/qoU6p02CmHqeE3ObmrSnRF0H0iu.jpg', '<iframe width="560" height="315" src="https://www.youtube.com/embed/7wd5KEaOtm4" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>', 7.5, 'Movie'),
  ('tt0468569', 'The Dark Knight', 'Batman regresa para continuar su guerra contra el crimen. Con la ayuda del teniente Jim Gordon y el Fiscal del Distrito Harvey Dent, Batman tiene como objetivo destruir el crimen organizado en la ciudad de Gotham. El triunvirato demuestra ser eficaz, pero pronto termina siendo presa del caos desencadenado por una nueva mente criminal que los aterrados ciudadanos conocen como Joker.', 'Action, Crime, Drama', '2008-07-16', 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/ri63imW8hLi8tP9sZOc1sP1Yk2T.jpg', 'https://image.tmdb.org/t/p/original/jfYVWfCsQ2wkif7KXD1Qsqxte2A.jpg', '<iframe width="560" height="315" src="https://www.youtube.com/embed/kmJLuwP3MbY" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>', 9.0, 'Movie'),
  ('tt0479143', 'Rocky Balboa', 'Corre el año 2005 y el campeón Mason Dixon no encuentra un rival a su altura en un boxeo devaluado. Han pasado 30 años desde que Rocky Balboa (Sylvester Stallone), un hombre sin futuro, tuvo un golpe de suerte que le brindó la oportunidad de boxear y llegar a enfrentarse en el cuadrilátero contra el campeón de entonces, Apollo Creed. El coraje y perseverancia de Rocky, tanto en la vida como en el cuadrilátero, brindó esperanza a millones de personas. Ahora, la gloria del que fue bicampeón del mundo ya se ha ido, y Rocky se pasa las tardes contando viejas historias a los clientes de su restaurante Adrians, que lleva el nombre de su ya fallecida esposa, por quien guarda un silencioso luto. Su hijo (Milo Ventimiglia) no desea pasar tiempo con él; se encuentra demasiado ocupado tratando de vivir su propia vida. El tiempo y los golpes han hecho más humilde a Rocky y en su corazón, él todavía es un luchador...', ' Drama, Sport ', '2006-12-20', 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/v1idhSQfaaXZqMKNWxfIc6t9zfL.jpg', 'https://image.tmdb.org/t/p/original/gcFhaI5IrKxvMs4TtvlHbYE4b0.jpg', '<iframe width="560" height="315" src="https://www.youtube.com/embed/8tab8fK2_3w" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>', 7.2, 'Movie'),
  ('tt0903747', 'Breaking Bad', 'Tras cumplir 50 años, Walter White (Bryan Cranston), un profesor de química de un instituto de Albuquerque, Nuevo México, se entera de que tiene un cáncer de pulmón incurable. Casado con Skyler (Anna Gunn) y con un hijo discapacitado (RJ Mitte), la brutal noticia lo impulsa a dar un drástico cambio a su vida: decide, con la ayuda de un antiguo alumno (Aaron Paul), fabricar anfetaminas y ponerlas a la venta. Lo que pretende es liberar a su familia de problemas económicos cuando se produzca el fatal desenlace.', 'Crime, Drama, Thriller', '2008-01-19', 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/1yeVJox3rjo2jBKrrihIMj7uoS9.jpg', 'https://image.tmdb.org/t/p/original/bzoZjhbpriBT2N5kwgK0weUfVOX.jpg', '<iframe width="560" height="315" src="https://www.youtube.com/embed/XZ8daibM3AE" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>', 9.5, 'Serie'),
  ('tt0944947', 'Game of Thrones', 'Juego de Tronos es una serie de televisión de drama y fantasía creada para la HBO por David Benioff y D. B. Weiss. Es una adaptación de la saga de novelas de fantasía Canción de Hielo y Fuego de George R. R. Martin. La primera de las novelas es la que da nombre a la serie. La serie, ambientada en los continentes ficticios de Westeros y Essos al final de un verano de una decada de duración, entrelaza varias líneas argumentales. La primera sigue a los miembros de varias casas nobles inmersos en una guerra civil por conseguir el Trono de Hierro de los Siete Reinos. La segunda trata sobre la creciente amenaza de un inminente invierno y sobre las temibles criaturas del norte. La tercera relata los esfuerzos por reclamar el trono de los últimos miembros exiliados de una dinastía destronada. A pesar de sus personajes moralmente ambiguos, la serie profundiza en los problemas de la jerarquía social, religión, lealtad, corrupción, sexo, guerra civil, crimen y castigo.', 'Adventure, Drama, Fantasy', '2011-04-17', 'https://image.tmdb.org/t/p/original/hDd5Zd9VMOqBeHa2agbnHZ98WWr.jpg', 'https://image.tmdb.org/t/p/original/AajildpFyqmqqCJiPKGp7yF2IaB.jpg', '<iframe width="560" height="315" src="https://www.youtube.com/embed/giYeaKsXnsI" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>', 9.5, 'Serie'),
  ('tt0974015', 'Justice League', 'Alimentado por su restaurada fe en la humanidad e inspirado por el acto desinteresado de Superman, Bruce Wayne recluta la ayuda de su recién encontrada aliada, Diana Prince, para enfrentarse a un enemigo aún mayor. Juntos, Batman y Wonder Woman trabajan deprisa para encontrar y reclutar un equipo de metahumanos para plantar cara a esta nueva amenaza creciente. Pero pese a la formación de esta liga de héroes sin precedentes - Batman, Wonder Woman, Aquaman, Cyborg y Flash, quizás sea demasiado tarde para salvar el planeta de un asalto de proporciones catastróficas.', 'Action, Adventure, Fantas', '2017-11-15', 'https://image.tmdb.org/t/p/original/hbkGah1KzCwBBIFk5KSs67tmpMx.jpg', 'https://image.tmdb.org/t/p/original/o5T8rZxoWSBMYwjsUFUqTt6uMQB.jpg', '<iframe width="560" height="315" src="https://www.youtube.com/embed/3cxixDgHUYw" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>', 7.0, 'Movie'),
  ('tt1442449', 'Spartacus', 'Traicionado por su país. Convertido en esclavo. Renacido como guerrero. Spartacus protagoniza la historia más gráfica y visceral del gladiador más famoso de Roma. Con un reparto estelar, asistimos a una mezcla única de acción, efectos gráficos y brutales batallas. Separado del amor de su vida, Spartacus tendrá que luchar por su supervivencia, participando en un espectáculo, donde el principal entretenimiento es la muerte. En un mundo de corrupción, violencia, sexo y fama acabará interviniendo en política y vivirá atormentado por el deseo de venganza.', 'Action, Adventure, Biography', '2010-01-22', 'https://image.tmdb.org/t/p/original/18FWPmsh2dULwMyWGjNDCUsmGRM.jpg', 'https://image.tmdb.org/t/p/original/kXgrZms2TwLTlaNS7uVAa3VPwNk.jpg', '<iframe width="560" height="315" src="https://www.youtube.com/embed/4WXDJPaHuR4" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>', 8.6, 'Serie'),
  ('tt1677720', 'Ready Player One', 'Año 2044. Wade Watts es un adolescente al que le gusta evadirse del cada vez más sombrío mundo real a través de una popular utopía virtual a escala global llamada Oasis, hasta que su excéntrico y multimillonario creador muere. Antes de morir, ofrece su fortuna como premio a una elaborada búsqueda del tesoro a través de los rincones más inhóspitos de su creación. Será el punto de partida para que Wade se enfrente a jugadores, poderosos enemigos corporativos y otros competidores despiadados dispuestos a hacer lo que sea, tanto dentro de Oasis como del mundo real, para hacerse con el premio.', 'Action, Adventure, Sci-Fi', '2018-03-28', 'https://image.tmdb.org/t/p/original/n4a2s86cfQfFoxjaixTLUGsuAE8.jpg', 'https://image.tmdb.org/t/p/original/4f9HoWfuSsQKpKDnbMcDEVAs1Rh.jpg', '<iframe width="560" height="315" src="https://www.youtube.com/embed/cSp1dM2Vj48" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>', null, 'Movie'),
  ('tt2306299', 'Vikings', 'Sigue las aventuras de Ragnar Lothbrok, el héroe más grande de su época. La serie narra las sagas de la banda de hermanos vikingos de Ragnar y su familia, cuando él se levanta para convertirse en el rey de las tribus vikingas. Además de ser un guerrero valiente, Ragnar encarna las tradiciones nórdicas de la devoción a los dioses, la leyenda dice que él era un descendiente directo de Odín, el dios de la guerra y los guerreros.', 'Action, Adventure, Drama ', '2013-03-03', 'https://image.tmdb.org/t/p/original/lKWqGKtBi3CMwXCdJw0YXjOAlxT.jpg', 'https://image.tmdb.org/t/p/original/siQeuaGIuikaObVnLiQq7zS7VuO.jpg', '<iframe width="560" height="315" src="https://www.youtube.com/embed/1j2sXLbzm9U" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>', 8.6, 'Serie'),
  ('tt2356180', 'Bhaag Milkha Bhaag', 'La verdadera historia del corredor campeón del mundo "Flying Sikh" y del atleta olímpico Milkha Singh, quien superó la masacre de su familia, la guerra civil durante la división India-Pakistán y la falta de vivienda para convertirse en uno de los atletas más icónicos de la India.', 'Biography, Drama, History', '2013-07-12', 'https://image.tmdb.org/t/p/original/nlshypM4QQfTqGcKHSMP2AAoMHC.jpg', 'https://image.tmdb.org/t/p/original/zEpOLEUDFiJqXznNAb6Lwa7iJP.jpg', '<iframe width="560" height="315" src="https://www.youtube.com/embed/0nR9JS2WsNg" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>', 8.3, 'Movie'),
  ('tt2575988', 'Silicon Valley', 'En la fiebre del oro de alta tecnología moderna de Silicon Valley, las personas más calificadas para tener éxito son los menos capaces de manejar el éxito. Parcialmente inspirada en las propias experiencias de Mike Judge como ingeniero de Silicon Valley a finales de los años 80, Silicon Valley es una comedia de situación estadounidense que se centra en torno a seis programadores que están viviendo juntos y tratando de hacer algo grande en el Silicon Valley.', 'Comedy', '2014-04-06', 'https://image.tmdb.org/t/p/original/uVccw0ypOFErjYSTNJ7eJmRt50T.jpg', 'https://image.tmdb.org/t/p/original/ndhrAoDsKSGlrAHEV5bDZ3JOqYI.jpg', '<iframe width="560" height="315" src="https://www.youtube.com/embed/69V__a49xtw" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>', 8.6, 'Serie'),
  ('tt2582802', 'Whiplash', 'El objetivo de Andrew Neiman, un joven y ambicioso baterista de jazz, es triunfar en el elitista Conservatorio de Música de la Costa Este en el que estudia. Marcado por el fracaso de la carrera literaria de su padre, Andrew alberga sueños de grandeza. Terence Fletcher, un profesor conocido tanto por su talento como por sus rigurosos métodos de enseñanza, dirige el mejor conjunto de jazz del Conservatorio. Cuando Fletcher elige a Andrew y para formar parte del conjunto musical que dirige, cambia para siempre la vida del joven. La pasión de Andrew por alcanzar la perfección se convierte en obsesión, al tiempo que su despiadado profesor lo lleva al límite de su capacidad y de su salud mental.', 'Drama, Music', '2014-10-10', 'https://image.tmdb.org/t/p/original/wTCi2hhbeFrKwLVELbLWlWwD2UG.jpg', 'https://image.tmdb.org/t/p/original/6bbZ6XyvgfjhQwbplnUh1LSj1ky.jpg', '<iframe width="560" height="315" src="https://www.youtube.com/embed/Df1xkYYbYrY" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>', 8.5, 'Movie'),
  ('tt3398228', 'BoJack Horseman', 'Conoce al caballo más querido de los 90… 20 años después. Vive en Los Ángeles donde humanos y animales antropomórficos coexisten, BoJack Horseman es la historia de un hombre (bueno, un caballo-hombre) que llegó muy rápido a la cima y ahora tiene que averiguar qué hacer.', 'Animation, Comedy, Drama', '2014-08-22', 'https://image.tmdb.org/t/p/original/wEp7ec8OudlngZ5dhoqSHJUDFdq.jpg', 'https://image.tmdb.org/t/p/original/2UVzBgmqs7Y94Dl42VSFx5xfRQN.jpg', '<iframe width="560" height="315" src="https://www.youtube.com/embed/i1eJMig5Ik4" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>', 8.5, 'Serie'),
  ('tt3783958', 'La La Land', 'Mia (Emma Stone), una joven aspirante a actriz que trabaja como camarera mientras acude a castings, y Sebastian (Ryan Gosling), un pianista de jazz que se gana la vida tocando en sórdidos tugurios, se enamoran, pero su gran ambición por llegar a la cima en sus carreras artísticas amenaza con separarlos.', 'Comedy, Drama, Music', '2017-01-13', 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/i712GLJklSVeuuNiz4egs7L1BvF.jpg', 'https://image.tmdb.org/t/p/original/nKQ7d55SdHuf1XyCRt5Xdpe3R9r.jpg', '<iframe width="560" height="315" src="https://www.youtube.com/embed/0pdqf4P9MB8" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>', 8.1, 'Movie'),
  ('tt4158110', 'Mr. Robot', 'Sigue a un misterioso anarquista que recluta a un joven programador de computadoras (Malek) que sufre de un trastorno antisocial y se conecta a la gente pirateándolos.', 'Crime, Drama, Thriller', '2015-05-27', 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/esN3gWb1P091xExLddD2nh4zmi3.jpg', 'https://image.tmdb.org/t/p/original/7Y0qTgjbkKvSZuQhtgbQmuntlCX.jpg', '<iframe width="560" height="315" src="https://www.youtube.com/embed/xIBiJ_SzJTA" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>', 8.6, 'Serie'),
  ('tt4508902', 'One Punch Man', 'La historia tiene lugar en una de las metrópolis ficticias de la Tierra, la Ciudad Z en Japón. El mundo está lleno de extraños monstruos que misteriosamente aparecen y causan muchos desastres. Saitama, el protagonista, es un poderoso superhéroe que derrota fácilmente a los monstruos u otros villanos con un único golpe. Debido a esto, Saitama ha encontrado aburrida su fuerza y siempre está tratando de encontrar rivales más poderosos que le puedan igualar. En sus aventuras se encuentra con nuevos amigos, enemigos y su propio discípulo, el cíborg Genos, y se une a la Asociación de Héroes para ganar fama por todas sus acciones para prevenir el mal. A pesar de derrotar a muchos enemigos poderosos que los principales héroes, incluso los de la Asociación de Héroes, son incapaces de derrotar, Saitama es incapaz de conseguir el reconocimiento de sus acciones en general. La mayoría de la gente lo discrimina por su apariencia física normal y algunos lo acusan de ser un héroe falso. Sólo un pequeño número de individuos reconocen su increíble talento y humildad hacia los demás.', 'Animation, Action, Comedy', '2015-10-04', 'https://image.tmdb.org/t/p/original/iXcaYJZlK2uDnLiTt5HlY2a0vuL.jpg', 'https://image.tmdb.org/t/p/original/s0w8JbuNNxL1YgaHeDWih12C3jG.jpg', '<iframe width="560" height="315" src="https://www.youtube.com/embed/RzmFKUDOUgw" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>', 9.0, 'Serie'),
  ('tt4680240', 'Club de Cuervos', 'El patriarca de una importante familia murió y sus herederos pelean para decidir quién asumirá el control de su adorado equipo de fútbol: Los cuervos de Nuevo Toledo. Egos, temperamentos y balones salen disparados en esta entrega del director, los productores y la estrella de “Nosotros los Nobles”, reunidos para darle vida a esta, aún más, absurda familia.', 'Comedy, Drama', '2015-08-07', 'https://image.tmdb.org/t/p/original/4gzTDVtC74UU1iMDCmGNiTzZ8Ej.jpg', 'https://image.tmdb.org/t/p/original/lduFzkGMUNc8j2cNCPIVPVyA9q8.jpg', '<iframe width="560" height="315" src="https://www.youtube.com/embed/9x3c8P3ooik" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>', 8.1, 'Serie'),
  ('tt4954522', 'Raw', 'Justine, una joven de 16 años, vive en una familia donde todos son veterinarios y vegetarianos. Es una estudiante brillante y prometedora, pero al ingresar en la facultad de veterinaria descubre un mundo decadente, despiadado y peligrosamente seductor. Durante la primera semana, obsesionada por encajar con sus compañeros de clase, se aleja de los principios que le han inculcado su familia, y come carne cruda por primera vez. Las consecuencias no tardan en llegar, y la joven empezará a desvelar su verdadera naturaleza.', 'Drama, Horror', '2016-10-07', 'https://image.tmdb.org/t/p/original/nsspHXM9tobnIMj8770vHLHPrKw.jpg', 'https://image.tmdb.org/t/p/original/qV1pUZAEdfX3sDb8jnkCjRQhXHG.jpg', '<iframe width="560" height="315" src="https://www.youtube.com/embed/gFlXVX2af_Y" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>', 7.0, 'Movie'),
  ('tt6257970', 'The End of the F***ing World', 'Un psicópata adolescente y una chica rebelde con sed de aventura emprenden un accidentado viaje por carretera en esta serie de humor negro basada en una novela gráfica.', 'Comedy, Drama', '2017-10-24', 'https://image.tmdb.org/t/p/original/xzwwzmXbz6n2Y3fc0GbjqGiFQPm.jpg', 'https://image.tmdb.org/t/p/original/up1HuhhJnzrJ8El0ZJqpKNf0piL.jpg', '<iframe width="560" height="315" src="https://www.youtube.com/embed/SqILm2JuHx4" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>', 8.4, 'Serie');

COMMIT;
